# Generated by Django 2.1.7 on 2019-07-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tobmag1scrumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalstatus',
            options={'verbose_name_plural': 'Goal Status'},
        ),
        migrations.AlterModelOptions(
            name='scrumygoals',
            options={'verbose_name_plural': 'Scrumy Goals'},
        ),
        migrations.AlterModelOptions(
            name='scrumyhistory',
            options={'verbose_name_plural': 'Scrumy History'},
        ),
    ]
